#!/usr/bin/env bash
#
# Install the nightly audio ingest as a launchd agent that runs from a deploy
# clone of this repository.
#
#   ops/launchd/install.sh                 # track main
#   ops/launchd/install.sh --ref <branch>  # track another pushed branch
#   ops/launchd/install.sh --uninstall     # remove the agent, the clone and its .env
#
# Layout, all outside the folders macOS privacy protection guards:
#
#   ~/Library/Application Support/pressd/
#     nightly.sh   copied from ops/launchd/nightly.sh; updates the clone, runs it
#     ingest/      git clone, detached at origin/<ref>, plus a copy of .env (0600)
#   ~/Library/LaunchAgents/com.pressd.audio-ingest.plist
#   ~/Library/Logs/pressd/{audio-ingest,preflight}.log
#
# Why a clone: launchd cannot read ~/Desktop, where the working copy lives
# (TCC, "Operation not permitted", exit 126 — verified 2026-09-29), and a
# working copy would run whatever branch or half-finished edit is checked out.
# The clone runs what is merged, and picks up new merges on its own each night.
#
# Why this tests before it installs: the previous agent (removed in 10ac442)
# ran for weeks doing nothing. launchd gives jobs a bare PATH and none of the
# terminal's privacy grants, so a job that works in a shell can fail every
# night under launchd, and that one recorded 'ok' each time. This runs the
# ingest's --preflight *as a launchd job*, through nightly.sh, from the clone —
# the exact path the nightly run takes — and installs nothing unless it passes.
#
# Scheduling: StartCalendarInterval, 00:30 *local* time — two hours before the
# GitHub predictions (02:30 PT) on Pacific time, further ahead in other zones.
# If the laptop is asleep then, launchd runs the job on the next wake (missed
# intervals coalesce into one run), so a closed lid delays the ingest rather
# than skipping it. worker/audio_health.py goes red in GitHub if a run fails or
# none happens for 36h.
#
# Secrets: the clone gets a copy of this repo's .env. Re-run this script after
# changing .env, or the nightly job keeps the old values.
#
# PRESSD_DEPLOY_REMOTE overrides the clone source (default: this repo's origin,
# over HTTPS so launchd needs no SSH agent). It exists to test the installer
# against a local repository without pushing anything.
#
set -euo pipefail

LABEL="com.pressd.audio-ingest"
PREFLIGHT_LABEL="$LABEL.preflight"
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
BASE="$HOME/Library/Application Support/pressd"
CLONE="$BASE/ingest"
LOGDIR="$HOME/Library/Logs/pressd"
AGENTS="$HOME/Library/LaunchAgents"
DOMAIN="gui/$(id -u)"
PLIST="$AGENTS/$LABEL.plist"

REF="main"
MODE="install"
while [ $# -gt 0 ]; do
  case "$1" in
    --ref)       REF="${2:?--ref needs a branch name}"; shift 2 ;;
    --uninstall) MODE="uninstall"; shift ;;
    *)           echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

xml_escape() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }
unload() { launchctl bootout "$DOMAIN/$1" 2>/dev/null || true; }

# write_plist <label> <path> <log> <schedule|once> [extra program args...]
write_plist() {
  local label="$1" path="$2" log="$3" when="$4"; shift 4
  local args="" a
  for a in "$@"; do args="$args        <string>$(xml_escape "$a")</string>"$'\n'; done
  local trigger
  if [ "$when" = "schedule" ]; then
    trigger='    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>0</integer>
        <key>Minute</key>
        <integer>30</integer>
    </dict>'
  else
    trigger='    <key>RunAtLoad</key>
    <true/>'
  fi
  cat > "$path" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by ops/launchd/install.sh in the pressd repo — edit that, not this. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$label</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$(xml_escape "$BASE/nightly.sh")</string>
$args    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PRESSD_DEPLOY_REF</key>
        <string>$(xml_escape "$REF")</string>
        <key>PRESSD_UPDATE_YTDLP</key>
        <string>1</string>
    </dict>
$trigger
    <key>Nice</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$(xml_escape "$log")</string>
    <key>StandardErrorPath</key>
    <string>$(xml_escape "$log")</string>
</dict>
</plist>
PLIST
  plutil -lint -s "$path"
}

if [ "$MODE" = "uninstall" ]; then
  unload "$LABEL"
  rm -f "$PLIST"
  # The clone holds a copy of .env; leaving it behind would strand secrets.
  case "$BASE" in */Library/"Application Support"/pressd) rm -rf "$BASE" ;; esac
  echo "Removed $LABEL, its plist, and $BASE (clone + .env copy). Logs kept in $LOGDIR."
  exit 0
fi

[ -f "$REPO/.env" ] || { echo "No .env in $REPO — the nightly job needs one to reach the database." >&2; exit 1; }
mkdir -p "$BASE" "$LOGDIR" "$AGENTS"

# ── 1. The deploy clone ─────────────────────────────────────────────────────────
if [ -n "${PRESSD_DEPLOY_REMOTE:-}" ]; then
  REMOTE="$PRESSD_DEPLOY_REMOTE"
else
  # HTTPS, even if the working copy uses SSH: the repo is public, and a launchd
  # job has no SSH agent to authenticate with.
  REMOTE="$(git -C "$REPO" remote get-url origin | sed -E 's#^git@github\.com:#https://github.com/#')"
fi
if [ ! -d "$CLONE/.git" ]; then
  echo "Cloning $REMOTE into $CLONE…"
  git clone --quiet "$REMOTE" "$CLONE"
else
  git -C "$CLONE" remote set-url origin "$REMOTE"
fi
git -C "$CLONE" fetch --quiet origin "$REF"
git -C "$CLONE" checkout --quiet --force --detach "origin/$REF"
AT="$(git -C "$CLONE" log -1 --format='%h %s')"
echo "Clone at origin/$REF: $AT"

# Refuse to install a job that would run the old ingest — no canary, no PATH for
# node/ffmpeg, 'ok' on every failure. That is the job that was dead for five weeks.
if [ ! -f "$CLONE/ops/launchd/nightly.sh" ] || ! grep -q "def preflight" "$CLONE/worker/audio_ingest.py"; then
  cat >&2 <<REFUSE

origin/$REF ($AT) does not contain the nightly audio ingest yet, so there is
nothing safe to schedule. Nothing installed. Merge that change into $REF, or
install from a pushed branch that has it:

    ops/launchd/install.sh --ref <branch>
REFUSE
  exit 1
fi

install -m 600 "$REPO/.env" "$CLONE/.env"
install -m 755 "$CLONE/ops/launchd/nightly.sh" "$BASE/nightly.sh"

# ── 2. Preflight, as launchd will run it ────────────────────────────────────────
PF_PLIST="$(mktemp -d)/$PREFLIGHT_LABEL.plist"
PF_LOG="$LOGDIR/preflight.log"
: > "$PF_LOG"
unload "$PREFLIGHT_LABEL"
write_plist "$PREFLIGHT_LABEL" "$PF_PLIST" "$PF_LOG" once --preflight
echo "Running the preflight under launchd (fetch, canary download + analysis, ~1 min)…"
launchctl bootstrap "$DOMAIN" "$PF_PLIST"

code=""
for _ in $(seq 1 150); do            # up to 5 minutes
  sleep 2
  info="$(launchctl print "$DOMAIN/$PREFLIGHT_LABEL" 2>/dev/null || true)"
  state="$(printf '%s\n' "$info" | sed -n 's/^[[:space:]]*state = //p' | head -1)"
  code="$(printf '%s\n' "$info" | sed -n 's/^[[:space:]]*last exit code = //p' | head -1)"
  if [ "$state" = "not running" ] && [ -n "$code" ] && [ "$code" != "(never exited)" ]; then
    break
  fi
done
unload "$PREFLIGHT_LABEL"
rm -f "$PF_PLIST"

echo "──── preflight output (launchd context) ────"
cat "$PF_LOG"
echo "────────────────────────────────────────────"

if [ "$code" != "0" ]; then
  echo "Preflight failed under launchd (exit: ${code:-timed out}). Nothing scheduled." >&2
  if grep -q "Operation not permitted" "$PF_LOG"; then
    echo "macOS privacy protection blocked a path the job needs — see the output above." >&2
  fi
  exit 1
fi

# ── 3. The nightly agent ────────────────────────────────────────────────────────
unload "$LABEL"
write_plist "$LABEL" "$PLIST" "$LOGDIR/audio-ingest.log" schedule
launchctl bootstrap "$DOMAIN" "$PLIST"

cat <<DONE

Installed $LABEL — nightly at 00:30 local, or on the next wake if the Mac is asleep.
  runs        origin/$REF from $CLONE (updated each night)
  log         $LOGDIR/audio-ingest.log
  run now     launchctl kickstart -p $DOMAIN/$LABEL
  status      launchctl print $DOMAIN/$LABEL | grep -E 'state|last exit'
  uninstall   ops/launchd/install.sh --uninstall
DONE
