"""Thread creation and the review→post mirror (PLAN_discussions.md §3, §5.1).

Lives outside `routers/` because two routers need it: `discussions` creates a
thread when someone posts, and `albums` has to keep a written review in step
with its post. A router importing another router to share a helper is how that
turns into a cycle.

Why a review is a real Post row and not a synthetic one assembled at read time
-----------------------------------------------------------------------------
Reviews were the conversation before threads existed — on a record two people
have both reviewed, the discussion has already started, and a thread that opens
with "be the first" is simply wrong. They could be unioned in when a thread is
read, which would avoid any duplication, but then they would have no post id,
and a review is exactly the thing people want to reply to and like.

So `album.review` stays the canonical text and this mirrors it into the thread.
That is a sync point, and sync points rot — this one is affordable because a
review has one owner and exactly two write paths — `albums.save_review` and
its delete twin. `review` is deliberately absent from ALBUM_MUTABLE_FIELDS, so
the generic PATCH cannot reach it. Contrast `album.subject_key`, which is
written from five places and therefore uses a mapper event instead.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import text as _sql
from sqlmodel import Session

from .models import Post, Thread

SPOILER_FLAGS_TO_BLUR = 3


def display_for(session: Session, subject_type: str, key: str) -> tuple[str, str | None, str | None]:
    """Title, subtitle and art for a thread, denormalised at creation (§3).

    Prefers a copy that actually has cover art — the row that happens to sort
    first is often a stub someone imported without one.
    """
    if subject_type == "album":
        row = session.execute(_sql(
            "SELECT album_name, artist, album_art_url FROM album WHERE subject_key = :k"
            " ORDER BY (album_art_url IS NULL), id LIMIT 1"), {"k": key}).first()
        return (row[0], row[1], row[2]) if row else (key.split("||")[-1], None, None)
    row = session.execute(_sql(
        "SELECT s.title, a.album_name, a.album_art_url FROM song s"
        " JOIN album a ON a.id = s.album_id WHERE s.track_id = :t"
        " ORDER BY (a.album_art_url IS NULL), s.id LIMIT 1"), {"t": key}).first()
    return (row[0], row[1], row[2]) if row else (f"track {key}", None, None)


def get_or_create_thread(session: Session, subject_type: str, key: str) -> Thread:
    """Lazily, on first use. Most subjects are never discussed, and a row per
    album in the catalogue would turn "is anyone talking about this?" into a
    scan (§3)."""
    hit = session.execute(_sql(
        "SELECT id FROM thread WHERE subject_type = :s AND subject_key = :k"),
        {"s": subject_type, "k": key}).first()
    if hit:
        return session.get(Thread, hit[0])
    title, subtitle, art = display_for(session, subject_type, key)
    thread = Thread(subject_type=subject_type, subject_key=key,
                    title=title, subtitle=subtitle, art_url=art)
    session.add(thread)
    session.commit()
    session.refresh(thread)
    return thread


def thread_summary(session: Session, thread: Thread) -> dict | None:
    """The record's numbers, computed on read rather than written into a post.

    This replaced a seeded prose post that said things like "3 people have rated
    this, averaging 8.37". That sentence was true the day it was written and
    wrong the next morning — it had to be regenerated by hand every time the
    numbers moved, which is not a thing anyone will remember to do. Numbers
    belong in a response, not in a row.

    Song scores are averaged **per track across users** before being compared,
    the way global_rating does it, so the favourite is the track the room likes
    rather than the track one person scored hardest.
    """
    if thread.subject_type != "album":
        return None

    agg = session.execute(_sql("""
        SELECT AVG(score), COUNT(DISTINCT user_id)
        FROM album
        WHERE subject_key = :k AND status = 'rated' AND score IS NOT NULL
    """), {"k": thread.subject_key}).first()
    if not agg or agg[1] in (0, None):
        return None

    tracks = session.execute(_sql("""
        SELECT s.title, AVG(s.score) AS m
        FROM song s JOIN album a ON a.id = s.album_id
        WHERE a.subject_key = :k AND s.score IS NOT NULL AND s.track_id IS NOT NULL
        GROUP BY s.track_id, s.title
        ORDER BY m DESC
    """), {"k": thread.subject_key}).fetchall()

    def track(row):
        return {"title": row[0], "score": round(float(row[1]), 1)} if row else None

    return {
        "mean_score": round(float(agg[0]), 2),
        "raters": agg[1],
        "top_track": track(tracks[0]) if tracks else None,
        # Only worth naming a worst track when there is more than one to lose.
        "bottom_track": track(tracks[-1]) if len(tracks) > 1 else None,
    }


def _recount(session: Session, thread_id: int) -> None:
    """Post count and last activity, recomputed rather than nudged.

    A review can appear, change and vanish, and each of those would need its own
    increment — counting is cheap here and cannot drift.
    """
    row = session.execute(_sql(
        "SELECT COUNT(*), MAX(created_at) FROM post"
        " WHERE thread_id = :t AND deleted_at IS NULL AND kind <> 'system'"),
        {"t": thread_id}).first()
    thread = session.get(Thread, thread_id)
    if thread:
        thread.post_count = row[0] or 0
        thread.last_post_at = row[1]
        session.add(thread)
        session.commit()


def sync_review_post(session: Session, album) -> None:
    """Mirror this album copy's review into the record's thread.

    Called after any write that could touch `album.review`. Idempotent, and
    quiet on failure — a thread is a consequence of a review, and losing the
    mirror must never cost someone the review itself.
    """
    try:
        key = album.subject_key
        if not key:
            return
        body = (album.review or "").strip()

        existing = session.execute(_sql("""
            SELECT p.id, p.thread_id FROM post p JOIN thread t ON t.id = p.thread_id
            WHERE t.subject_type = 'album' AND t.subject_key = :k
              AND p.user_id = :u AND p.kind = 'review'
            LIMIT 1"""), {"k": key, "u": album.user_id}).first()

        if not body:
            # Cleared. Soft-delete rather than remove, so any replies it drew
            # still have something to hang from.
            if existing:
                post = session.get(Post, existing[0])
                if post and not post.deleted_at:
                    post.deleted_at = datetime.utcnow()
                    session.add(post)
                    session.commit()
                    _recount(session, existing[1])
            return

        if existing:
            post = session.get(Post, existing[0])
            if post:
                if post.body != body:
                    post.body = body
                    post.edited_at = datetime.utcnow()
                # A review that was cleared and rewritten comes back rather
                # than leaving a tombstone where the text now is.
                post.deleted_at = None
                session.add(post)
                session.commit()
                _recount(session, existing[1])
            return

        thread = get_or_create_thread(session, "album", key)
        post = Post(thread_id=thread.id, user_id=album.user_id, kind="review", body=body)
        # Carry the review's own timestamp so it sorts where it was written,
        # not where it was mirrored — these are months old.
        if album.review_at:
            post.created_at = album.review_at
        session.add(post)
        session.commit()
        _recount(session, thread.id)
    except Exception as e:  # pragma: no cover
        session.rollback()
        print(f"[sync_review_post] album {getattr(album, 'id', '?')} failed: {e}")


def sync_comment_post(session: Session, comment, album) -> None:
    """Mirror a comment on someone's rating into the record's thread, as a reply
    to their review.

    A comment on a friend's album is a reply to what they wrote about it, and
    the thing they wrote is now a post. Leaving the two apart means the same
    exchange reads as a conversation on one screen and silence on the other.

    Two conditions, and both matter:

      There has to be a review post to answer. A comment is a response to what
      the owner said; with nothing said, a mirrored reply would dangle from
      nothing, so it stays a comment and nothing is lost.

      The commenter has to have earned the room. `thread_access` is the whole
      product argument — a thread is people who finished the record — and a
      friend can comment on your rating without having heard the album. Their
      words stay on your page rather than entering a room they cannot read.

    Only ever called for *new* comments. The existing rows were written under a
    friends-only expectation and are never backfilled: publishing them after the
    fact would be a privacy regression, not a feature (PLAN_discussions.md §3.1).
    """
    from .deps import thread_access

    try:
        key = getattr(album, "subject_key", None)
        if not key or album.user_id == comment.user_id:
            return
        allowed, _ = thread_access(session, comment.user_id, "album", key)
        if not allowed:
            return

        review = session.execute(_sql("""
            SELECT p.id FROM post p JOIN thread t ON t.id = p.thread_id
            WHERE t.subject_type = 'album' AND t.subject_key = :k
              AND p.user_id = :owner AND p.kind = 'review' AND p.deleted_at IS NULL
            LIMIT 1"""), {"k": key, "owner": album.user_id}).first()
        if not review:
            return

        root = session.get(Post, review[0])
        reply = Post(thread_id=root.thread_id, user_id=comment.user_id,
                     parent_id=root.id, body=comment.body)
        session.add(reply)
        session.commit()
        session.refresh(reply)

        comment.post_id = reply.id
        root.reply_count = (root.reply_count or 0) + 1
        session.add_all([comment, root])
        session.commit()
        _recount(session, root.thread_id)
    except Exception as e:  # pragma: no cover
        session.rollback()
        print(f"[sync_comment_post] comment {getattr(comment, 'id', '?')} failed: {e}")


def remove_comment_post(session: Session, comment) -> None:
    """Take the mirrored reply with the comment. Soft, like every other delete
    here, so anything hanging off it still has an anchor."""
    try:
        if not getattr(comment, "post_id", None):
            return
        post = session.get(Post, comment.post_id)
        if not post or post.deleted_at:
            return
        post.deleted_at = datetime.utcnow()
        session.add(post)
        if post.parent_id:
            root = session.get(Post, post.parent_id)
            if root:
                root.reply_count = max(0, (root.reply_count or 1) - 1)
                session.add(root)
        session.commit()
        _recount(session, post.thread_id)
    except Exception as e:  # pragma: no cover
        session.rollback()
        print(f"[remove_comment_post] comment {getattr(comment, 'id', '?')} failed: {e}")


def post_track_note(session: Session, user_id: int, song, body: str) -> int | None:
    """Put a note written during the rating flow into that track's thread.

    One per person per track, replaced on a re-rate rather than stacked — the
    note is what you think of the song, not a log of every time you said it.

    Returns the post id, or None when there is nothing to attach to: a song
    whose `track_id` never resolved has no global identity and therefore no
    room to be in.
    """
    body = (body or "").strip()
    if not getattr(song, "track_id", None):
        return None
    try:
        key = str(song.track_id)
        existing = session.execute(_sql("""
            SELECT p.id, p.thread_id FROM post p JOIN thread t ON t.id = p.thread_id
            WHERE t.subject_type = 'track' AND t.subject_key = :k
              AND p.user_id = :u AND p.kind = 'track_note'
            LIMIT 1"""), {"k": key, "u": user_id}).first()

        if not body:
            if existing:
                post = session.get(Post, existing[0])
                if post and not post.deleted_at:
                    post.deleted_at = datetime.utcnow()
                    session.add(post)
                    session.commit()
                    _recount(session, existing[1])
            return None

        if existing:
            post = session.get(Post, existing[0])
            if post:
                if post.body != body:
                    post.body = body
                    post.edited_at = datetime.utcnow()
                post.deleted_at = None
                session.add(post)
                session.commit()
                _recount(session, existing[1])
                return post.id
            return None

        thread = get_or_create_thread(session, "track", key)
        post = Post(thread_id=thread.id, user_id=user_id, kind="track_note", body=body)
        session.add(post)
        session.commit()
        session.refresh(post)
        _recount(session, thread.id)
        return post.id
    except Exception as e:  # pragma: no cover
        session.rollback()
        print(f"[post_track_note] song {getattr(song, 'id', '?')} failed: {e}")
        return None
