import type { Album } from './types'

export const mockAlbums: Album[] = [
  {
    id: 1,
    albumName: 'good kid, m.A.A.d city',
    artist: 'Kendrick Lamar',
    year: 2012,
    status: 'rated',
    score: 9.29,
    theme: 10,
    replayValue: 8,
    production: 7,
    distinctness: 8,
    genre: 'Hip-Hop',
    subGenre1: 'Conscious Hip-Hop',
    subGenre2: null,
    albumArtUrl: null,
    totalTracks: 12,
    spotifyId: null,
    dateAdded: '2024-01-01',
    dateRated: '2024-01-01',
    songs: [
      { id: 1, title: 'Sherane a.k.a Master Splinter\'s Daughter', trackNumber: 1, score: 7.7, aScore: 7.96, durationMs: 234000, spotifyPopularity: 72, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 2, title: 'Bitch, Don\'t Kill My Vibe', trackNumber: 2, score: 8.9, aScore: 9.19, durationMs: 310000, spotifyPopularity: 85, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 3, title: 'Backseat Freestyle', trackNumber: 3, score: 8.6, aScore: 8.88, durationMs: 214000, spotifyPopularity: 82, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 4, title: 'The Art of Peer Pressure', trackNumber: 4, score: 8.0, aScore: 8.23, durationMs: 315000, spotifyPopularity: 75, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 5, title: 'Money Trees', trackNumber: 5, score: 9.2, aScore: 9.54, durationMs: 386000, spotifyPopularity: 90, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 6, title: 'Poetic Justice', trackNumber: 6, score: 8.2, aScore: 8.46, durationMs: 245000, spotifyPopularity: 78, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 7, title: 'good kid', trackNumber: 7, score: 8.4, aScore: 8.65, durationMs: 340000, spotifyPopularity: 77, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 8, title: 'm.A.A.d city', trackNumber: 8, score: 9.0, aScore: 9.31, durationMs: 349000, spotifyPopularity: 88, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 9, title: 'Swimming Pools (Drank)', trackNumber: 9, score: 8.6, aScore: 8.88, durationMs: 313000, spotifyPopularity: 86, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 10, title: 'Sing About Me, I\'m Dying of Thirst', trackNumber: 10, score: 9.4, aScore: 9.77, durationMs: 719000, spotifyPopularity: 89, explicit: false, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 11, title: 'Real', trackNumber: 11, score: 7.8, aScore: 8.08, durationMs: 348000, spotifyPopularity: 70, explicit: false, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
      { id: 12, title: 'Compton', trackNumber: 12, score: 7.6, aScore: 7.88, durationMs: 247000, spotifyPopularity: 68, explicit: true, spotifyId: null, albumId: 1, artist: 'Kendrick Lamar' },
    ],
  },
  {
    id: 2,
    albumName: 'IGOR',
    artist: 'Tyler, The Creator',
    year: 2019,
    status: 'rated',
    score: 8.74,
    theme: 9,
    replayValue: 8,
    production: 10,
    distinctness: 8,
    genre: 'Neo-Soul',
    subGenre1: 'Alt-R&B',
    subGenre2: null,
    albumArtUrl: null,
    totalTracks: 12,
    spotifyId: null,
    dateAdded: '2024-02-10',
    dateRated: '2024-02-10',
    songs: [
      { id: 13, title: 'IGOR\'S THEME', trackNumber: 1, score: 7.0, aScore: 7.23, durationMs: 148000, spotifyPopularity: 74, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 14, title: 'EARFQUAKE', trackNumber: 2, score: 8.0, aScore: 8.23, durationMs: 175000, spotifyPopularity: 88, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 15, title: 'I THINK', trackNumber: 3, score: 8.3, aScore: 8.58, durationMs: 197000, spotifyPopularity: 85, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 16, title: 'EXACTLY WHAT YOU RUN FROM', trackNumber: 4, score: 6.0, aScore: 6.15, durationMs: 117000, spotifyPopularity: 65, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 17, title: 'RUNNING OUT OF TIME', trackNumber: 5, score: 8.6, aScore: 8.88, durationMs: 149000, spotifyPopularity: 82, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 18, title: 'NEW MAGIC WAND', trackNumber: 6, score: 8.8, aScore: 9.08, durationMs: 175000, spotifyPopularity: 79, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 19, title: 'A BOY IS A GUN*', trackNumber: 7, score: 8.8, aScore: 9.08, durationMs: 210000, spotifyPopularity: 83, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 20, title: 'PUPPET', trackNumber: 8, score: 8.3, aScore: 8.58, durationMs: 222000, spotifyPopularity: 76, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 21, title: 'WHAT\'S GOOD', trackNumber: 9, score: 7.5, aScore: 7.73, durationMs: 165000, spotifyPopularity: 72, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 22, title: 'GONE, GONE / THANK YOU', trackNumber: 10, score: 8.8, aScore: 9.08, durationMs: 264000, spotifyPopularity: 87, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 23, title: 'I DON\'T LOVE YOU ANYMORE', trackNumber: 11, score: 6.5, aScore: 6.65, durationMs: 121000, spotifyPopularity: 68, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
      { id: 24, title: 'ARE WE STILL FRIENDS?', trackNumber: 12, score: 8.7, aScore: 8.96, durationMs: 208000, spotifyPopularity: 84, explicit: false, spotifyId: null, albumId: 2, artist: 'Tyler, The Creator' },
    ],
  },
  {
    id: 3,
    albumName: 'channel ORANGE',
    artist: 'Frank Ocean',
    year: 2012,
    status: 'listening',
    score: null,
    theme: null,
    replayValue: null,
    production: null,
    distinctness: null,
    genre: 'R&B',
    subGenre1: null,
    subGenre2: null,
    albumArtUrl: null,
    totalTracks: 17,
    spotifyId: null,
    dateAdded: '2024-03-01',
    dateRated: null,
    songs: [
      { id: 25, title: 'Start', trackNumber: 1, score: null, aScore: null, durationMs: 16000, spotifyPopularity: 60, explicit: false, spotifyId: null, albumId: 3, artist: 'Frank Ocean' },
      { id: 26, title: 'Thinkin Bout You', trackNumber: 2, score: 8.2, aScore: 8.46, durationMs: 201000, spotifyPopularity: 88, explicit: false, spotifyId: null, albumId: 3, artist: 'Frank Ocean' },
      { id: 27, title: 'Fertilizer', trackNumber: 3, score: null, aScore: null, durationMs: 60000, spotifyPopularity: 55, explicit: false, spotifyId: null, albumId: 3, artist: 'Frank Ocean' },
      { id: 28, title: 'Sierra Leone', trackNumber: 4, score: 7.5, aScore: 7.73, durationMs: 201000, spotifyPopularity: 72, explicit: false, spotifyId: null, albumId: 3, artist: 'Frank Ocean' },
      { id: 29, title: 'Sweet Life', trackNumber: 5, score: null, aScore: null, durationMs: 249000, spotifyPopularity: 82, explicit: false, spotifyId: null, albumId: 3, artist: 'Frank Ocean' },
    ],
  },
  {
    id: 4,
    albumName: 'Currents',
    artist: 'Tame Impala',
    year: 2015,
    status: 'to_listen',
    score: null,
    theme: null,
    replayValue: null,
    production: null,
    distinctness: null,
    genre: 'Pop',
    subGenre1: 'Psychedelic Pop',
    subGenre2: null,
    albumArtUrl: null,
    totalTracks: 13,
    spotifyId: null,
    dateAdded: '2024-03-15',
    dateRated: null,
    songs: [],
  },
]
